[{server,
  [{cacertfile, "/etc/erlang/certs/ca_certificate.pem"},
   {certfile,   "/etc/erlang/certs/node.pem"},
   {keyfile,    "/etc/erlang/certs/node.key"},
   {secure_renegotiate, true},
   {verify, verify_peer},
   {fail_if_no_peer_cert, true}]},
 {client,
  [{cacertfile, "/etc/erlang/certs/ca_certificate.pem"},
   {certfile,   "/etc/erlang/certs/node.pem"},
   {keyfile,    "/etc/erlang/certs/node.key"},
   {secure_renegotiate, true},
   {verify, verify_peer}]}].
